import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="flex justify-between items-center px-4 bg-zinc-900 text-white p-4">
          <h1 className="text-2xl font-bold">My Next.js App</h1>
          <ul className="flex space-x-4 mt-2">
            <li>
              <Link href="/" className="hover:underline">
                Home
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover:underline">
                About
              </Link>
            </li>
          </ul>
        </header>
        {children}
        <footer className="bg-zinc-900 text-white p-4 mt-auto">
          <p className="text-center">&copy; 2024 My Next.js App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
